# Generated by Django 5.0.6 on 2024-07-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameimagelink',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gamedate',
        ),
        migrations.AlterField(
            model_name='game',
            name='link1',
            field=models.CharField(max_length=20),
        ),
    ]
